import 'package:go_pharma/repos/product/product_model.dart';

List products = [
  Product(
    id: "1",
    name: "Product 1",
    supplier: "Supplier 1",
    inStock: true,
    price: 100.00,
    boolPrescriptionRequired: false,
  ),
  Product(
    id: "2",
    name: "Product 2",
    supplier: "Supplier 2",
    inStock: false,
    price: 9600.00,
    boolPrescriptionRequired: false,
  ),
  Product(
    id: "3",
    name: "Product 3",
    supplier: "Supplier 3",
    inStock: true,
    price: 2600.00,
    boolPrescriptionRequired: false,
  ),
  Product(
    id: "4",
    name: "Product 4",
    supplier: "Supplier 4",
    inStock: false,
    price: 180.00,
    boolPrescriptionRequired: false,
  ),
  Product(
    id: "5",
    name: "Product 5",
    supplier: "Supplier 5",
    inStock: true,
    price: 140.00,
    boolPrescriptionRequired: false,
  ),
  Product(
    id: "6",
    name: "Product 6",
    supplier: "Supplier 6",
    inStock: true,
    price: 14120.00,
    boolPrescriptionRequired: true,
  ),
  Product(
    id: "7",
    name: "Product 7",
    supplier: "Supplier 7",
    inStock: true,
    price: 40.00,
    boolPrescriptionRequired: true,
  ),
  Product(
    id: "8",
    name: "Product 8",
    supplier: "Supplier 8",
    inStock: false,
    price: 200.00,
    boolPrescriptionRequired: false,
  ),
];
